In [1]:
import pandas as pd

In [2]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
OHE = OneHotEncoder()

In [4]:
df = pd.DataFrame({'color':['Red','Green','Blue','Red','Green','Blue']})

In [54]:
df

   color
0    Red
1  Green
2   Blue
3    Red
4  Green
5   Blue

In [55]:
OHE1 = OHE.fit(df)

In [56]:
OHE1

OneHotEncoder()

In [57]:
OHE2 = OHE.fit_transform(df)

In [58]:
OHE2 = OHE2.toarray()

In [59]:
df2 = pd.DataFrame(OHE2,columns=OHE.get_feature_names_out())

In [60]:
df2

   color_Blue  color_Green  color_Red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          0.0        1.0
4         0.0          1.0        0.0
5         1.0          0.0        0.0

In [61]:
pd.concat([df,df2],axis=1)

   color  color_Blue  color_Green  color_Red
0    Red         0.0          0.0        1.0
1  Green         0.0          1.0        0.0
2   Blue         1.0          0.0        0.0
3    Red         0.0          0.0        1.0
4  Green         0.0          1.0        0.0
5   Blue         1.0          0.0        0.0

In [62]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [63]:
lbl_encoder

LabelEncoder()

In [64]:
lbl_encoder.fit_transform(df[['color']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 1, 0, 2, 1, 0])

In [65]:
lbl_encoder.transform([['Red']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [66]:
lbl_encoder.transform([['Green']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [67]:
lbl_encoder.transform([['Blue']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [68]:
## ORdinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [69]:
df3 = pd.DataFrame({'sizes':['small','medium','large']})

In [70]:
df3

    sizes
0   small
1  medium
2   large

In [71]:
oe = OrdinalEncoder()

In [74]:
oe=OrdinalEncoder(categories=[['small','medium','large']])

In [75]:
oe.fit_transform(df3[['sizes']])

array([[0.],
       [1.],
       [2.]])

In [79]:
oe.transform([['small']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

In [80]:
oe.transform([['large']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[2.]])

In [81]:
oe.transform([['medium']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])

## Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [1]:
# create a sample dataframe with a categorical variable and a target variable

import pandas as pd

df = pd.DataFrame({'city':['New York','London','Glassglow','New York','U K','London','Glassglow'],
      'Price':[500,400,300,300,200,100,400]})

In [2]:
df

        city  Price
0   New York    500
1     London    400
2  Glassglow    300
3   New York    300
4        U K    200
5     London    100
6  Glassglow    400

In [14]:
mean = df.groupby('city')['Price'].mean().to_dict()
print(mean)

{'Glassglow': 350.0, 'London': 250.0, 'New York': 400.0, 'U K': 200.0}

In [12]:
df['city_encoded'] = df['city'].map(mean)

In [13]:
df[['city','Price','city_encoded']]

        city  Price  city_encoded
0   New York    500         400.0
1     London    400         250.0
2  Glassglow    300         350.0
3   New York    300         400.0
4        U K    200         200.0
5     London    100         250.0
6  Glassglow    400         350.0

In [15]:
import seaborn as sns

In [16]:
df2 = sns.load_dataset('tips')

In [17]:
df2.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [23]:
mean1 = df2.groupby('smoker')['total_bill'].mean()

In [26]:
df2['new_bill'] = df2['smoker'].map(mean1)

In [27]:
df2[['total_bill','new_bill','smoker']]

     total_bill   new_bill smoker
0         16.99  19.188278     No
1         10.34  19.188278     No
2         21.01  19.188278     No
3         23.68  19.188278     No
4         24.59  19.188278     No
..          ...        ...    ...
239       29.03  19.188278     No
240       27.18  20.756344    Yes
241       22.67  20.756344    Yes
242       17.82  19.188278     No
243       18.78  19.188278     No

[244 rows x 3 columns]

In [28]:
# correlation

df3 = sns.load_dataset('healthexp')

In [29]:
df3

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

In [30]:
import numpy as np

In [37]:
df3.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [44]:
np.cov(df3[['Year','Spending_USD','Life_Expectancy']])

array([[ 1.09853246e+06,  1.11338028e+06,  1.13093049e+06, ...,
        -9.49023888e+04, -6.01204227e+03, -1.84486063e+06],
       [ 1.11338028e+06,  1.12946778e+06,  1.14839981e+06, ...,
        -1.76328732e+05, -8.02178708e+04, -2.06533966e+06],
       [ 1.13093049e+06,  1.14839981e+06,  1.16887319e+06, ...,
        -2.66135928e+05, -1.61973986e+05, -2.31023599e+06],
       ...,
       [-9.49023888e+04, -1.76328732e+05, -2.66135928e+05, ...,
         6.19017612e+06,  5.71820875e+06,  1.52428872e+07],
       [-6.01204227e+03, -8.02178708e+04, -1.61973986e+05, ...,
         5.71820875e+06,  5.28830381e+06,  1.39607817e+07],
       [-1.84486063e+06, -2.06533966e+06, -2.31023599e+06, ...,
         1.52428872e+07,  1.39607817e+07,  3.99007391e+07]])

In [45]:
df3.dtypes

Year                 int64
Country             object
Spending_USD       float64
Life_Expectancy    float64
dtype: object

In [48]:
df3['Spending_USD_1'] = pd.to_numeric(df3['Spending_USD'], errors='coerce')
df3['Life_Expectancy_1'] = pd.to_numeric(df3['Life_Expectancy'], errors='coerce')

# Now try
df3[['Year', 'Spending_USD_1', 'Life_Expectancy_1']].cov()

                           Year  Spending_USD_1  Life_Expectancy_1
Year                 201.098848    2.571883e+04          41.915454
Spending_USD_1     25718.827373    4.817761e+06        4166.800912
Life_Expectancy_1     41.915454    4.166801e+03          10.733902

In [49]:
df3['Life_Expectancy_1'].dtype

dtype('float64')

In [51]:
df3[['Year', 'Spending_USD_1', 'Life_Expectancy_1']].corr(method='pearson')

                       Year  Spending_USD_1  Life_Expectancy_1
Year               1.000000        0.826273           0.902175
Spending_USD_1     0.826273        1.000000           0.579430
Life_Expectancy_1  0.902175        0.579430           1.000000